autopep8==1.4.4
dj-database-url==0.5.0
Django==2.2.4
django-appconf==1.0.3
django-compressor==2.3
django-debug-toolbar==2.0
django-heroku==0.3.1
gunicorn==19.9.0
libsass==0.19.2
psycopg2==2.8.3
psycopg2-binary==2.8.3
pycodestyle==2.5.0
python-decouple==3.1
pytz==2019.2
rcssmin==1.0.6
rjsmin==1.1.0
six==1.12.0
sqlparse==0.3.0
whitenoise==4.1.3





Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bluemoon/Desktop/Mayan Studio/Development/heroku/mayanwebstudio/.venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/bluemoon/Desktop/Mayan Studio/Development/heroku/mayanwebstudio/.venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/Users/bluemoon/Desktop/Mayan Studio/Development/heroku/mayanwebstudio/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/bluemoon/Desktop/Mayan Studio/Development/heroku/mayanwebstudio/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/bluemoon/Desktop/Mayan Studio/Development/heroku/mayanwebstudio/.venv/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/bluemoon/Desktop/Mayan Studio/Development/heroku/mayanwebstudio/.venv/lib/python3.7/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/Users/bluemoon/Desktop/Mayan Studio/Development/heroku/mayanwebstudio/.venv/lib/python3.7/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/Users/bluemoon/Desktop/Mayan Studio/Development/heroku/mayanwebstudio/.venv/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/bluemoon/Desktop/Mayan Studio/Development/heroku/mayanwebstudio/.venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 579, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/bluemoon/Desktop/Mayan Studio/Development/heroku/mayanwebstudio/.venv/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/bluemoon/Desktop/Mayan Studio/Development/heroku/mayanwebstudio/.venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 572, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/bluemoon/Desktop/Mayan Studio/Development/heroku/mayanwebstudio/.venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'root'